### ISSUE TITLE
Octotiger fails to compile with GCC 5.3

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/octotiger#31]
When trying to build octotiger with GCC 5.3, I get compiler errors like these:
```
In file included from /home/users/khuck/src/octotiger/src/grid.hpp:19:0,
                 from /home/users/khuck/src/octotiger/src/roe.cpp:9:
/home/users/khuck/src/octotiger/src/taylor.hpp: In member function ‘taylor<N, T> taylor<N, T>::operator-() const’:
/home/users/khuck/src/octotiger/src/taylor.hpp:194:14: error: expected primary-expression before ‘]’ token
             [](T const& val)
              ^
/home/users/khuck/src/octotiger/src/taylor.hpp:194:18: error: expected primary-expression before ‘const’
             [](T const& val)
                  ^
```

**Comment by hkaiser** [comment]
Do you miss to specify the -std=c++11 flag to the compiler?

**Comment by khuck** [comment]
Yes, the c++14 flag is there:

```
[  7%] Building CXX object CMakeFiles/octotiger_exe.dir/src/eos.cpp.o
/usr/local/packages/gcc/5.3/bin/g++   -DBOOST_DISABLE_ASSERTS -DHPX_APPLICATION_EXPORTS -DHPX_APPLICATION_NAME=octotiger_exe -DHPX_APPLICATION_STRING=\"octotiger_exe\" -DHPX_DISABLE_ASSERTS -DHPX_PREFIX=\"/home/users/khuck/src/operation_gordon_bell/build-x86\" -DOCTOTIGER_HAVE_GRAV_PAR -std=c++14 -march=native -Wvector-operation-performance -Wno-attributes -Wno-deprecated-declarations  -O2 -g -DNDEBUG -I/home/users/khuck/src/hpx-lsu -I/home/users/khuck/src/operation_gordon_bell/build-x86 -I/home/users/khuck/src/hpx-lsu/apex/src/apex -I/home/users/khuck/src/hpx-lsu/examples -I/home/users/khuck/src/hpx-lsu/tests -I/home/users/khuck/src/operation_gordon_bell/Vc/include -I/usr/local/packages/boost/1.61_gcc-5.3/include -I/home/users/khuck/install/hwloc-1.8/include -I/home/users/khuck/src/octotiger/src -I/home/users/khuck/include    -std=c++14 -o CMakeFiles/octotiger_exe.dir/src/eos.cpp.o -c /home/users/khuck/src/octotiger/src/eos.cpp
In file included from /home/users/khuck/src/octotiger/src/grid.hpp:19:0,
                 from /home/users/khuck/src/octotiger/src/eos.hpp:12,
                 from /home/users/khuck/src/octotiger/src/eos.cpp:8:
/home/users/khuck/src/octotiger/src/taylor.hpp: In member function ‘taylor<N, T> taylor<N, T>::operator-() const’:
/home/users/khuck/src/octotiger/src/taylor.hpp:194:14: error: expected primary-expression before ‘]’ token
             [](T const& val)
              ^
/home/users/khuck/src/octotiger/src/taylor.hpp:194:18: error: expected primary-expression before ‘const’
             [](T const& val)
                  ^
make[2]: *** [CMakeFiles/octotiger_exe.dir/src/eos.cpp.o] Error 1
```

**Comment by DavidPfander-UniStuttgart** [comment]
I think there is a missing semicolon before that line.

Regards,
David

**Comment by hkaiser** [comment]
It was a missing comma - doh! Should be ok now.
