### ISSUE TITLE
Octotiger does not compile with gcc 6.3.1

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/octotiger#41]
In file included from /usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/immintrin.h:41:0,
                 from /home/diehlpk/git/octotiger/src/simd.hpp:13,
                 from /home/diehlpk/git/octotiger/src/grid.hpp:13,
                 from /home/diehlpk/git/octotiger/src/grid_fmm.cpp:7:
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/avxintrin.h: In constructor ‘simd_vector::simd_vector(double)’:
/usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/avxintrin.h:1216:1: error: inlining failed in call to always_inline ‘__m256d _mm256_set_pd(double, double, double, double)’: target specific option mismatch
 _mm256_set_pd (double __A, double __B, double __C, double __D)
 ^~~~~~~~~~~~~
In file included from /home/diehlpk/git/octotiger/src/grid.hpp:13:0,
                 from /home/diehlpk/git/octotiger/src/grid_fmm.cpp:7:
/home/diehlpk/git/octotiger/src/simd.hpp:23:40: note: called from here
 #define _mmx_set_pd(d)    _mm256_set_pd((d),(d),(d),(d))
                           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/home/diehlpk/git/octotiger/src/simd.hpp:65:10: note: in expansion of macro ‘_mmx_set_pd’
    v[i] =_mmx_set_pd(d);

**Comment by diehlpk** [comment]
For gcc 6.3.1 one have to add -msse4.1

**Comment by DavidPfander-UniStuttgart** [comment]
To me this looks like a build configuration issue. I attached a script that build octotiger, hpx and Vc on my machine (you have to change the paths and do a clone before it is useful).
[octotiger_complete_upgrade.txt](https://github.com/STEllAR-GROUP/octotiger/files/750379/octotiger_complete_upgrade.txt)
